### ISSUE TITLE
jss deploy command doesn't support custom port in deployUrl

### ISSUE THREAD

**Issue by AlenPelin** [Sitecore/jss#369] opened 2020-05-07 02:43 UTC
## Description
Executing `jss deploy items` command fails with error:
```
Sending package sitecore\package\JssReactWeb.1588818983231.manifest.zip to http://jss.dev.local:80/sitecore/api/jss/import...
Unexpected response from import service:
Status message: Forbidden
Body: Invalid authentication.
```

## Expected behavior
The items are deployed with no issues as usual.

## Steps To Reproduce
1. Consider vanilla solution that only responds to custom 8080 port where e.g. JssReactWeb sample app deploys well with `jss deploy items`
2. In the `scjssconfig.json` file modify the `deployUrl` to include the port i.e. `"deployUrl": "http://jss.dev.local:8080/sitecore/api/jss/import"`
3. Execute `jss deploy items`
4. See error above

## Why it is important
when Sitecore runs on custom port esp. when running in docker and there are multiple docker solutions on the same machine so you can't have them all running on the standard 80/443 ports.

## Your Environment

* Sitecore Version: `9.2` or `9.3`
* JSS Version: `11` or `12` or `13`
* Browser Name and version: N/A
* Operating System and version (desktop or mobile): Windows 10 and Windows Server 2019
* Link to your project (if available): N/A

**Comment by AlenPelin** [comment] 2020-05-07 02:45
It is quite likely the issue affects all the scenarios where authentication is verified.

**Comment by sc-illiakovalenko** [comment] 2020-07-02 10:36
@AlenPelin Deploy is working when you set custom port. But you don't need to set port :80 in url, because it's default http port,
and https default - :443, you can skip adding of default port.

**Comment by AlenPelin** [comment] 2020-07-02 15:05
@sc-illiakovalenko very good point, thanks ;) 

In the scenario above port 80 or 443 was used to simplify reproduction, in real life the port is different (for example, when running Sitecore in Docker).

**Comment by sc-illiakovalenko** [comment] 2020-07-02 22:05
@sc-illiakovalenko So, do you mean that deploy is not working using custom port? Because i tried to test it locally, and it's working, but without docker

**Comment by AlenPelin** [comment] 2020-07-03 06:54
The issue is still actual, you can't deploy items to solution that only responds to custom port. I have updated scenario to make it clearer.

**Comment by sc-illiakovalenko** [comment] 2020-07-03 09:03
@AlenPelin I can't reproduce it :)
My steps to reproduce.
1. Installed Sitecore 9.3
2. In IIS bind `http JssReactWeb` with port 8080

![image](https://user-images.githubusercontent.com/55081915/86452254-b87ea000-bd24-11ea-9be4-fd77cca26b91.png)

3. jss setup, my scjssconfig.json

4. jss deploy config

![image](https://user-images.githubusercontent.com/55081915/86452316-ca604300-bd24-11ea-9c8a-c1aa3905be1b.png)

5. jss deploy app -c -d - working

6. jss deploy items - working


Are you using some proxy? In my case I can't reproduce it on clean instance without any additional setup.
Can you cleanup and run: jss setup, and there set custom port? instead of modifying config file.

**Comment by AlenPelin** [comment] 2020-07-03 14:28
Thank you, I will double check and let you know.

**Comment by AlenPelin** [comment] 2020-07-03 14:29
In my case I used localhost:8080 instead of custom host name. Maybe it was the case.

**Comment by sc-illiakovalenko** [comment] 2020-07-06 09:57
@AlenPelin I tested it, using localhost:8080, it's still working, deploy completed successfully.
I close this issue, I believe you have something in your configs, probably proxy.... If you will find
a stable scenario, and will provide detailed information, feel free to open issue.
Using clean instance - everything is working as expected.

![image](https://user-images.githubusercontent.com/55081915/86580900-034c2200-bf88-11ea-8aa6-3906e4071200.png)

**Comment by coreyasmith** [comment] 2020-07-14 21:15
As @AlenPelin predicted, this is an issue in Docker when using a port other than `80` for your container such as `44001`.

## `scjssconfig.json`:

```json
{
  "sitecore": {
    "instancePath": "..\\..\\..\\..\\docker\\data\\cm",
    "apiKey": "{9893AC66-DF21-4EBF-8F36-DE2303DF5291}",
    "deploySecret": "28253754763375480530856519086189",
    "deployUrl": "http://localhost:44001/sitecore/api/jss/import",
    "layoutServiceHost": "http://localhost:44001"
  }
}
```

With debug security both on the client and server you can see what the issue is.

## Server log:

```
2020-07-14 15:33:26.130 [system]       WARN  ( 548) [JSS] - Server-side deployment security debugging is enabled. Ensure this is OFF in production.
2020-07-14 15:33:26.130 [system]       WARN  ( 548) [JSS] - Server-side security factors: this-is-sitecore, http://localhost/sitecore/api/jss/import, HPmtgVdzWypGsT4JaxOnSPf/7/uD+RVWfGuVnFdmhsM=
2020-07-14 15:33:26.130 [system]       WARN  ( 548) [JSS] - For authentication to succeed, these factors must match the client-side factors (use --debugSecurity to see them), and the shared secret must match.
```

## Client log:

```
Security debugging is enabled. Do not use this unless absolutely necessary.
Deployment secret: 9fsorm3qnjp5wqzhy8wb68ngojh3sf1a2v1g7x185hx
Deployment security factors: this-is-sitecore,http://localhost:44001/sitecore/api/jss/import,HPmtgVdzWypGsT4JaxOnSPf/7/uD+RVWfGuVnFdmhsM=
Deployment HMAC: U34dcPDyYBBwPeybYmtJV2ptuh2qpfoVDJziAgLsdwk=
```

Notice that the server is missing the port in the URL portion of its security factor (`http://localhost/sitecore/api/jss/import`), but the client has it (`http://localhost:44001/sitecore/api/jss/import`).

Sitecore uses `HttpContext.Current.Request.Url` to get the URL portion of the security factor. Sitecore runs on port `80` in Docker, so the external port (`44001` in this case) will never be reflected in `HttpContext.Current.Request.Url`.

It's possible to work around this by adding a `clientDeployUrl` attribute to your JSS `<app />` node in config that matches the `deployUrl` from your `scjssconfig.json` like this:

```xml
<configuration>
  <sitecore>
    <javaScriptServices>
      <apps>
        <app name="this-is-sitecore"
             clientDeployUrl="http://localhost:44001/sitecore/api/jss/import"
        />
      </apps>
    </javaScriptServices>
  </sitecore>
</configuration>
```

Then create a custom `ImportServiceAuthenticator` to use the `clientDeployUrl` attribute instead of `HttpContext.Current.Request.Url` to authenticate requests to the import service like this:

```csharp
using System;
using System.Web;
using Sitecore.JavaScriptServices.AppServices.ImportService;
using Sitecore.JavaScriptServices.Configuration;

namespace ThisIsSitecore
{
    public class DockerFriendlyImportServiceAuthenticator : ImportServiceAuthenticator
    {
        private readonly IConfigurationResolver _configResolver;

        public DockerFriendlyImportServiceAuthenticator(IConfigurationResolver configResolver)
            : base(configResolver)
        {
            _configResolver = configResolver ?? throw new ArgumentNullException(nameof(configResolver));
        }

        protected override bool ValidateHmac(string hmac, string appName, string secret, string[] secretFactors, bool debug)
        {
            var appConfiguration = _configResolver.ResolveForName(appName);
            var clientDeployUrl = appConfiguration?.Attributes["clientDeployUrl"];
            if (secretFactors == null || string.IsNullOrWhiteSpace(clientDeployUrl))
            {
                return base.ValidateHmac(hmac, appName, secret, secretFactors, debug);
            }

            for (var i = 0; i < secretFactors.Length; i++)
            {
                if (secretFactors[i] == null) continue;
                if (!secretFactors[i].Equals(HttpContext.Current.Request.Url.ToString())) continue;
                secretFactors[i] = clientDeployUrl;
            }

            return base.ValidateHmac(hmac, appName, secret, secretFactors, debug);
        }
    }
}
```

Create a custom configurator to register it with Sitecore's IoC container:

```csharp
using Microsoft.Extensions.DependencyInjection;
using Sitecore.DependencyInjection;
using Sitecore.JavaScriptServices.AppServices.ImportService;

namespace ThisIsSitecore
{
    public class ThisIsSitecoreConfigurator : IServicesConfigurator
    {
        public void Configure(IServiceCollection serviceCollection)
        {
            serviceCollection.AddSingleton<IImportServiceAuthenticator, DockerFriendlyImportServiceAuthenticator>();
        }
    }
}
```

And patch the configurator into Sitecore's config:

```xml
<configuration>
  <sitecore>
    <services>
      <configurator type="ThisIsSitecore.ThisIsSitecoreConfigurator, ThisIsSitecore" />
    </services>
  </sitecore>
<configuration>
```

Ideally we wouldn't need such hacky workarounds though.

**Comment by OlegJytnik** [comment] 2020-07-15 15:14
Similar issue has been fixed in upcoming JSS 14 for the cases when Sitecore is running behind the reverse proxy. In this case we taking The X-Forwarded-* headers into account. The same applicable for Docker environment when for example traefik reverse proxy is used as a frontdoor for the docker cluster. We will log issue with Docker port forwarding into the backlog. I think we can use app setting approach or introduce environment variable (easy to pass through the docker-compose).

**Comment by AlenPelin** [comment] 2020-07-16 15:13
Thanks @OlegJytnik please keep in mind that it is reproducible even without traefik reverse proxy, same happens with simple `docker-compose`.

**Comment by sc-illiakovalenko** [comment] 2020-10-23 11:04
@AlenPelin Issue fixed and will be released in JSS 15. I'm closing it.

**Closed by sc-illiakovalenko** 2020-10-23 11:04 UTC
