### ISSUE TITLE
Cachable component added multiple times causes exception

### ISSUE THREAD

**Issue by mquekel** [Sitecore/jss#158] opened 2019-02-14 08:51 UTC
## Description
We are encountering a bug in JSS 11. The following Exception is thrown when one component with the same datasource is placed on a page more then once.
This happens only when caching is applied to the component. The caching settings in my case are Cachable + Vary by data.

This produces the following error.

`Exception: System.ArgumentException
Message: An item with the same key has already been added.
Source: mscorlib
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary2.Insert(TKey key, TValue value, Boolean add)
   at Sitecore.LayoutService.Presentation.Pipelines.RenderRendering.RenderJsonFromCache.Render(String cacheKey, TextWriter writer, RenderRenderingArgs args, RenderedJsonRenderingContext renderedRenderingContext)
   at Sitecore.LayoutService.Presentation.Pipelines.RenderRendering.RenderJsonFromCache.Process(RenderRenderingArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Mvc.Pipelines.PipelineService.RunPipeline[TArgs](String pipelineName, TArgs args)
   at Sitecore.Mvc.Pipelines.Response.RenderPlaceholder.PerformRendering.Render(String placeholderName, TextWriter writer, RenderPlaceholderArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.LayoutService.ItemRendering.PlaceholderRenderingService.RenderPlaceholder(PlaceholderDefinition placeholderDefinition, IRenderingConfiguration renderingConfiguration)
   at System.Linq.Enumerable.WhereSelectListIterato2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterato1.MoveNext()
   at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable1 source)
   at Sitecore.LayoutService.Presentation.Pipelines.RenderJsonRendering.RenderPlaceholders.SetResult(RenderJsonRenderingArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.LayoutService.Presentation.Pipelines.RenderJsonRendering.RenderJsonRenderingPipeline.GetResult(RenderJsonRenderingArgs args)
   at Sitecore.LayoutService.Presentation.JsonDataRenderer.Render(TextWriter writer)
   at Sitecore.Mvc.Pipelines.Response.RenderRendering.ExecuteRenderer.Render(Renderer renderer, TextWriter writer, RenderRenderingArgs args)`

## Steps To Reproduce
1. Select or create a Json Rendering under /sitecore/layout/Renderings 
2. Go to the caching options and select **Cachable** and **Vary By Data**
3. Create or modify a page in the Experience Editor
4. Add the rendering where caching is applied and select a datasource (or leave empty)
5. Add the same component with the same datasource again
6. Publish the page
7. Request this page via the Layoutservice

## Your Environment
* Sitecore Version: 9.0.1 
* JSS Version: JSS 11.0

A Sitecore support ticket describing this problem is created with support ticket ID 525460

**Comment by jbluemink** [comment] 2019-02-18 12:54
There is a patch available https://github.com/sitecoresupport/Sitecore.Support.311073/releases

**Comment by kamsar** [comment] 2019-03-04 21:32
This should be patched in the next release.

**Comment by aweber1** [comment] 2019-03-06 12:06
Closing as there is a support patch available for current Sitecore versions and as Kam mentioned, the issue is fixed in Sitecore 9.2.

**Closed by aweber1** 2019-03-06 12:06 UTC
Labels: bug, requires layout service changes
