### ISSUE TITLE
JSS importer return duplicate ID error when try to import component with param fields defined as 

### ISSUE THREAD

**Issue by chaturangar** [Sitecore/jss#203] opened 2019-06-11 03:05 UTC
## Description
This issue actually occurs when I have used RenderingParameterDefinition way of defining Params instead of just using String. Ex:

```
params: [ 
      { name: 'small', displayName: "Small", type: CommonFieldTypes.Number }
    ],
```

And when I try to import this into Sitecore, it throws following mention error for the first time. Then if I ran it for the second time, it goes successfully.

**NOTE**: after second import everything works fine but issue occurs when try to import it for the first time ONLY.

> Exception thrown while importing JSS app Exception: System.InvalidOperationException Message: The ID {066A79EA-C450-5853-B44E-7125E977BDF0} has been used more than once during import. This likely means two imported items have the same id value, or two items of the same type (e.g. templates) share the same name. Details: template Body1ColRow Rendering Parameters, template Body1ColRow Rendering Parameters Source: Sitecore.JavaScriptServices.AppServices at Sitecore.JavaScriptServices.AppServices.Data.IdManager.AssertIdIsUnused(ID id, String idUsageDescription) at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ProcessTemplates.CreateTemplate(TemplateDef templateDef, Item parent, Item multilistRoot, AppConfiguration app, IdManager idManager) at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ProcessTemplates.d__11.MoveNext() at System.Linq.Buffer1..ctor(IEnumerable1 source) at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source) at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ProcessTemplates.Process(ImportPipelineArgs args) at (Object , Object ) at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args) at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain, Boolean failIfNotExists)
> at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain) at Sitecore.JavaScriptServices.AppServices.Pipelines.Import.ImportPipeline.Import(ImportPipelineArgs args) at Sitecore.JavaScriptServices.AppServices.ImportService.ImportJob.ProcessRetries(ImportPipelineArgs args) at Sitecore.JavaScriptServices.AppServices.ImportService.ImportJob.StartImportInternal()
> 
> Import is complete.
> 
> IMPORT ERROR(S) OCCURRED! Exception thrown while importing JSS app Exception: System.InvalidOperationException Message: The ID {066A79EA-C450-5853-B44E-7125E977BDF0} has been used more than once during import. This likely means two imported items have the same id value, or two items of the same type (e.g. templates) share the same name. Details: template Body1ColRow Rendering Parameters, template Body1ColRow Rendering Parameters Source: Sitecore.JavaScriptServices.AppServices at

## Expected behavior
Import should not throw duplicate ID error for the first time import also

## Steps To Reproduce
1. Create a jss component with Param field defined using RenderingParameterDefinition
2. run jss deploy app -c -d
3. See error
4. run jss deploy app -c -d
5. doesn't throw any error

## Possible Fix
When we import it for the second time (without wipe out the content), importer doesn't return any errors and gets imported successfully

## Your Environment
* Sitecore Version: 9.0.2 (rev. 180604)
* JSS Version: 11.0.1
* Browser Name and version: Chrome
* Operating System and version (desktop or mobile): Windows 10

**Comment by sc-dawidrutkowski** [comment] 2019-09-06 12:31
This issue seems to be already fixed. I'm closing this one as I'm unable to reproduce it on the latest code.

**Closed by sc-dawidrutkowski** 2019-09-06 12:31 UTC

**Comment by jfmanuel** [comment] 2020-05-15 19:58
Hi everyone,

I find the same issue. 
But this time I have not created any templates with params.
There is an existing template that has the params that causes the issue it is the styleguide templates when your try to setup new JSS app.
And actually I am not using it. When the JSS import kicks in it post an issue something like this
![image](https://user-images.githubusercontent.com/18147890/82091202-863fc180-9729-11ea-968c-8882b1a4f5b9.png)

**Comment by gary1125** [comment] 2020-12-22 04:41
I have the same issue. I ran the commend twice but the issue still exists.
