### ISSUE TITLE
Angular Issue | ss create my-first-jss-app angular

### ISSUE THREAD

**Issue by tmamedbekov** [Sitecore/jss#59] opened 2018-09-19 21:48 UTC
When running angular template, generation executes just fine, once `jss start`, it breaks.

> ** Angular Live Development Server is listening on localhost:3001, open your browser on http://localhost:3001/ **
>  10% building modules 3/3 modules 0 active[HPM] Proxy created: [ '/data', '/sitecore' ]  ->  http://localhost:3043
> Watching for changes to component factory sources in src/app/components...
> Enabling TypeScript transpilation for the manifest...
> path or pattern './sitecore/pipelines/**/*.patch.js' did not match any files.
> copied media from: ./data/media/img/sc_logo.png to: sitecore/manifest/data/media/img/sc_logo.png
> copied media from: ./data/media/img/jss_logo.png to: sitecore/manifest/data/media/img/jss_logo.png
> copied media from: ./data/media/files/jss.pdf to: sitecore/manifest/data/media/files/jss.pdf
> Manifest has been generated and written to ./sitecore/manifest/sitecore-import.json
> 🔌  Disconnected Layout Service initializing...⏳
> Manifest manager is watching for manifest source file changes...
> JSS Disconnected-mode Proxy is listening on port 3043.
>                                                                                           
> Date: 2018-09-19T21:42:28.275Z
> Hash: 2ae07028cb9e9069b8b4
> Time: 5501ms
> chunk {main} main.js, main.js.map (main) 1.93 kB [initial] [rendered]
> chunk {polyfills} polyfills.js, polyfills.js.map (polyfills) 682 bytes [initial] [rendered]
> chunk {runtime} runtime.js, runtime.js.map (runtime) 5.22 kB [entry] [rendered]
> chunk {styles} styles.js, styles.js.map (styles) 148 kB [initial] [rendered]
> chunk {vendor} vendor.js, vendor.js.map (vendor) 325 kB [initial] [rendered]
> 
> ERROR in node_modules/apollo-angular/types.d.ts(10,58): error TS2304: Cannot find name 'Exclude'.
> 
> ℹ ｢wdm｣: Failed to compile.

**Comment by kamsar** [comment] 2018-09-21 15:31
Duplicate of https://github.com/apollographql/apollo-angular/issues/770

Alter your package.json to use `apollo-angular` `1.1.1` instead of `^1.1.1`, or install using Yarn (whose lock will avoid this issue. Will look into upgrading for GA.

**Comment by kamsar** [comment] 2018-09-21 17:40
RTM version of angular sample will be using angular 6.1, which resolves this issue (`apollo-angular` was allowed to float to a version compatible only with angular 6.1). Anyone else with the issue, simply refer to `"apollo-angular": "1.1.1"` in package.json instead of `^1.1.1`

**Closed by kamsar** 2018-09-21 17:40 UTC
